openapi: 3.0.0
info:
  title: Next.js API with Swagger
  version: 1.0.0
  description: API documentation for a Next.js project
servers:
  - url: "http://localhost:3000"
components:
  schemas:
    AuthParamsDto:
      type: object
      required:
        - phone
        - password
      properties:
        phone:
          type: string
          example: "+1234567890"
        password:
          type: string
          example: "yourpassword"
paths:
  /api/auth/login:
    post:
      summary: User login
      description: Authenticate a user using phone and password.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthParamsDto"
      responses:
        "200":
          description: Successful login, returns JWT token
  /api/auth/user-info:
    get:
      security:
        - bearerAuth: []
      tags:
        - Authentication
      summary: Retrieve the logged in user info
      description: Fetch a user from the database using their ID.
      responses:
        "200":
          description: The user information.
  /api/auth/register:
    post:
      summary: User registration
      description: Register a new user.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthParamsDto"
      responses:
        "200":
          description: Successful login, returns JWT token
