import type { Metadata } from "next";
import "./globals.css";
import ClientToastify from "@/components/ClientToastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body dir="rtl">
        {children}
        <ClientToastify />
      </body>
    </html>
  );
}
